### ISSUE TITLE
Lista de partidos con sentencias, muestra múltiples copias de los partidos

### ISSUE THREAD

**Issue by jmcastagnetto** [aniversarioperu/otorongo.club#12]
En la página https://otorongo.club/2021/partidos/sentencias/, los partidos aparecen múltiples veces, y con distintos totales.

Esto se puede observar tanto con el código siguiente, como con una captura de pantalla de dicha página

```
library(tidyverse)
library(rvest)

url <- "https://otorongo.club/2021/partidos/sentencias/"

resumen <- url %>% 
  read_html() %>% 
  html_nodes("table") %>% 
  html_table(fill = TRUE, trim = TRUE) %>% 
  .[[1]] %>% 
  janitor::clean_names() %>% 
  group_by(organizacion_politica) %>% 
  tally()

resumen
# A tibble: 22 x 2
#   organizacion_politica                              n
# * <chr>                                          <int>
# 1 ACCION POPULAR                                    29
# 2 ALIANZA PARA EL PROGRESO                          29
# 3 AVANZA PAIS - PARTIDO DE INTEGRACION SOCIAL       24
# 4 DEMOCRACIA DIRECTA                                29
# 5 EL FRENTE AMPLIO POR JUSTICIA, VIDA Y LIBERTAD    26
# 6 FRENTE POPULAR AGRICOLA FIA DEL PERU - FREPAP     29
# 7 FUERZA POPULAR                                    29
# 8 JUNTOS POR EL PERU                                29
# 9 PARTIDO APRISTA PERUANO                            6
#10 PARTIDO DEMOCRATICO SOMOS PERU                    29
# … with 12 more rows
```

Esta captura de pantalla fue tomada hoy 2021-02-09 a las ~08:43h

![screenshot-otorongo club-2021 02 09-08_43_41](https://user-images.githubusercontent.com/364668/107375405-b51b7600-6ab6-11eb-9841-28ba63e767bf.png)

**Comment by aniversarioperu** [comment]
la lista incluye partidos separados por region. Las multiples copias es {{ Partido }} {{ Region }} pero se me olvido de poner la region en el template:
<img width="1176" alt="Screen Shot 2021-02-11 at 10 28 10" src="https://user-images.githubusercontent.com/5254076/107658318-014fed00-6c54-11eb-8d97-03f36d9a0ca9.png">
Corregido, gracias por avisar!
