### ISSUE TITLE
agregar robots.txt para evitar indexing de json data

### ISSUE THREAD

**Issue by aniversarioperu** [aniversarioperu/otorongo.club#13]
producir el json data requiere de esfuerzo significativo del CPU, mejor que no lo indexen para evitar gasto de recursos. Se gasta el CPU :-D

**Comment by unrecano** [comment]
Sí claro con respecto a eso ¿sería mejor exportar el archivo o continua siendo una URL accesible?

**Comment by aniversarioperu** [comment]
creo que cualquiera de los modos esta bien

**Comment by unrecano** [comment]
Se crea el pull request #15 para resolver este issue.

**Comment by aniversarioperu** [comment]
gracias!
