### ISSUE TITLE
Lista de partidos con sentencias sin región definida (None) causan comportamiento inconsistente al filtrar

### ISSUE THREAD

**Issue by jmcastagnetto** [aniversarioperu/otorongo.club#16]
Esta lista, al incluir la Región en el nombre (podría haber sido un campo también), corrige el problema observado en #12, pero presenta un problema nuevo.

Hay registros que presentan "**None**" como Región, que es algo usual cuando Python no encuentra valor para una variable.

![Listados mostrando "None"](https://user-images.githubusercontent.com/364668/107887319-4766b400-6ed3-11eb-9fa2-fc9f45804977.png)

Si se aplica uno de los filtros disponibles, por ejemplo "Todas las regiones":

![Selección de filtros disponibles](https://user-images.githubusercontent.com/364668/107887358-990f3e80-6ed3-11eb-85fe-4144d3cb98c0.png)

Se obtiene el listado, pero sin los registros que contienen "**None**", lo cual tiene lógica, conociendo el stack que están empleando:

![Filtrado con "Todas las regiones"](https://user-images.githubusercontent.com/364668/107887385-bba15780-6ed3-11eb-8e02-51116261f286.png)

El URL para la página de arriba es https://otorongo.club/2021/partidos/sentencias/?region=TODAS, con el parámetro de región seleccionada.

Dedido a como se esta manejando los filtros y lo que se presenta en el desplegable (no hay opción de seleccionar registros sin región definida), estos que contienen "**None**" ya no vuelven a aparecer sino hasta que se recarga de cero (sin parámetros en el URL).

Sugerencia: tratar los valores no definidos (**Missing**) y hacer una imputación con una etiqueta apropiada (ej. "Región no definida")

**Comment by jmcastagnetto** [comment]
Si la región fuera un campo, posiblemente el problema observado al exportar JSON (#17), se solucionaría.

**Comment by aniversarioperu** [comment]
los candidatos sin region son los que postula al parlamento andino o a la presidencia de la republica

**Comment by rmaceissoft** [comment]
@aniversarioperu 
Me gustaría hacer una observación.
Si sumamos el "total de antecedentes" de todos los registros de un mismo partido politico en las distintas regiones, el total coincide con el valor del registro que tiene "None" en la region,
Parece como si los registros **<partido politico> - None**, representaran el total de cada partido?

Coincido con la observación de @jmcastagnetto:
Las siguientes paginas deberían mostrar los mismos registros:
- https://otorongo.club/2021/partidos/sentencias/
- https://otorongo.club/2021/partidos/sentencias/?region=TODAS

Ademas, creo que los resultados deberían ser agrupados por partido politico cuando se muestren todas las regiones. Algo asi...
<img width="639" alt="Screen Shot 2021-02-14 at 5 23 14 PM" src="https://user-images.githubusercontent.com/476427/107890920-8acc1d00-6ee9-11eb-9525-1a69ac37f4de.png">

**Comment by rmaceissoft** [comment]
> los candidatos sin region son los que postula al parlamento andino o a la presidencia de la republica

Seria bueno reflejar esta observación a la hora de listar los registros. Asumo que con esto se refiere a casos como el siguiente?
<img width="1130" alt="Screen Shot 2021-02-14 at 5 44 19 PM" src="https://user-images.githubusercontent.com/476427/107891387-56a62b80-6eec-11eb-896c-6c7b760d6ed6.png">

**Comment by aniversarioperu** [comment]
he tratado de arreglarlo. He puesto region = "NoDefinida" a los candidatos que no tienen region porque postulan al parlamento andino o postulan a la presidencia y/o vicepresidencias. Ya esta en produccion. Me comentan que les parece.

**Comment by aniversarioperu** [comment]
creo que ya podemos cerrrar este issue @jmcastagnetto  ?

**Comment by jmcastagnetto** [comment]
Si, por favor, y gracias por resolver el problema.
