### ISSUE TITLE
Al exportar la lista en https://otorongo.club/2021/partidos/sentencias/, JSON no incluye la región del partido

### ISSUE THREAD

**Issue by jmcastagnetto** [aniversarioperu/otorongo.club#17]
El problema #12 se solucionó en parte (ver #16 para un nuevo problema) el listado de los partidos, pero, cuando se quiere exportar la información, esta carece de la información de región, ya sea en el nombre del partido o como un campo extra.

Este es un fragmento del JSON exportado hace unos minutos, donde se puede ver el problema que inicialmente se observó en #12:

```
[
  {
    "nombre": "ALIANZA PARA EL PROGRESO",
    "total_antecedentes": 40,
    "antecedentes_penales": 7,
    "antecedentes_obligaciones": 33
  },
  {
    "nombre": "UNION POR EL PERU",
    "total_antecedentes": 34,
    "antecedentes_penales": 19,
    "antecedentes_obligaciones": 15
  },
  {
    "nombre": "PARTIDO MORADO",
    "total_antecedentes": 34,
    "antecedentes_penales": 3,
    "antecedentes_obligaciones": 31
  },
  {
    "nombre": "VICTORIA NACIONAL",
    "total_antecedentes": 30,
    "antecedentes_penales": 8,
    "antecedentes_obligaciones": 22
  },
  {
    "nombre": "AVANZA PAIS - PARTIDO DE INTEGRACION SOCIAL",
    "total_antecedentes": 28,
    "antecedentes_penales": 12,
    "antecedentes_obligaciones": 16
  },
  {
    "nombre": "DEMOCRACIA DIRECTA",
    "total_antecedentes": 28,
    "antecedentes_penales": 5,
    "antecedentes_obligaciones": 23
  },
  {
    "nombre": "PARTIDO POLITICO NACIONAL PERU LIBRE",
    "total_antecedentes": 26,
    "antecedentes_penales": 12,
    "antecedentes_obligaciones": 14
  },
  {
    "nombre": "ACCION POPULAR",
    "total_antecedentes": 24,
    "antecedentes_penales": 9,
    "antecedentes_obligaciones": 15
  },
  {
    "nombre": "PARTIDO DEMOCRATICO SOMOS PERU",
    "total_antecedentes": 19,
    "antecedentes_penales": 8,
    "antecedentes_obligaciones": 11
  },
  {
    "nombre": "PODEMOS PERU",
    "total_antecedentes": 18,
    "antecedentes_penales": 5,
    "antecedentes_obligaciones": 13
  },
  {
    "nombre": "VICTORIA NACIONAL",
    "total_antecedentes": 16,
    "antecedentes_penales": 3,
    "antecedentes_obligaciones": 13
  },
  {
    "nombre": "FUERZA POPULAR",
    "total_antecedentes": 14,
    "antecedentes_penales": 5,
    "antecedentes_obligaciones": 9
  },
  {
    "nombre": "EL FRENTE AMPLIO POR JUSTICIA, VIDA Y LIBERTAD",
    "total_antecedentes": 14,
    "antecedentes_penales": 10,
    "antecedentes_obligaciones": 4
  },
  {
    "nombre": "PARTIDO NACIONALISTA PERUANO",
    "total_antecedentes": 12,
    "antecedentes_penales": 4,
    "antecedentes_obligaciones": 8
  },
  {
    "nombre": "ALIANZA PARA EL PROGRESO",
    "total_antecedentes": 11,
    "antecedentes_penales": 0,
    "antecedentes_obligaciones": 11
  },
  {
    "nombre": "PARTIDO MORADO",
    "total_antecedentes": 10,
    "antecedentes_penales": 0,
    "antecedentes_obligaciones": 10
  },
  {
    "nombre": "PARTIDO POPULAR CRISTIANO - PPC",
    "total_antecedentes": 10,
    "antecedentes_penales": 6,
    "antecedentes_obligaciones": 4
  },
  {
    "nombre": "JUNTOS POR EL PERU",
    "total_antecedentes": 10,
    "antecedentes_penales": 5,
    "antecedentes_obligaciones": 5
  },
...
```

**Comment by jmcastagnetto** [comment]
Aún el JSON está incorrecto, acabo de tomar la siguiente captura de pantalla

![image](https://user-images.githubusercontent.com/364668/107902700-2f178900-6f15-11eb-9e1f-37c704298768.png)

Y esta también, que muestra como el nombre de los partidos se repite y no incluye la región

![image](https://user-images.githubusercontent.com/364668/107902794-76057e80-6f15-11eb-8c00-100fa1b56f49.png)

**Comment by aniversarioperu** [comment]
la region esta como "distrito".  El JNE usa el termino distrito.

**Comment by jmcastagnetto** [comment]
En https://votoinformado.jne.gob.pe/voto/Busqueda/PersonalizadaResultado?paramUrl=0MnZ2UKxUHTXhKmjVCPRCtV3rWovtLd2 veo:

![image](https://user-images.githubusercontent.com/364668/107904128-e8c42900-6f18-11eb-8e01-366aaff4c383.png)

Y cuando veo el detalle de uno de los candidatos al azar (básicamente el primero que salió en la búsqueda anterior) https://votoinformado.jne.gob.pe/voto/HojaVida/HojaVida?codigo=s4GqDD04lIc%3d

![image](https://user-images.githubusercontent.com/364668/107904209-1b6e2180-6f19-11eb-91cf-88910f4ffb8c.png)

¿Están usando una fuente de datos distinta? pues ese punto no es claro en la descripción en vuestro sitio.

**Comment by jmcastagnetto** [comment]
Cambiando "distrito" por "departamento" o "región" estaria OK, pues no veo que el JNE use la denominación que indicas, explicitamente.

**Comment by jmcastagnetto** [comment]
OK, veo que están usando https://plataformaelectoral.jne.gob.pe donde JNE usa el término "Distrito Electoral" que es, en general, el Departamento (a excepción del que engloba a los peruanos en el extranjero)

**Comment by aniversarioperu** [comment]
lo cambien por `region`
