### ISSUE TITLE
Datos en formato CSV o JSON

### ISSUE THREAD

**Issue by jmcastagnetto** [aniversarioperu/otorongo.club#6]
Creo que seria muy útil el tener la información que han recopilado en un formato que se pueda usar para análisis y visualizaciones.

Algo como lo que puse en https://github.com/jmcastagnetto/peru-candidatos-2021-infofinanciera, basado en vuestra información en https://twitter.com/AniversarioPeru/status/1342705785269346305 (que es lo que tienen en dos de las tablas en vuestro sitio).

En particular seria interesante tener los datos de la tabla en https://otorongo.club/2021/sentencias/

**Comment by aniversarioperu** [comment]
buena idea quiza @unrecano se anime?

**Comment by unrecano** [comment]
Entiendo que la idea sería el poder exportar los datos de la tabla (https://otorongo.club/2021/sentencias/) en un formato como csv.

**Comment by jmcastagnetto** [comment]
> Entiendo que la idea sería el poder exportar / descargar los datos de la tabla (https://otorongo.club/2021/sentencias/) en un formato como csv o un json.

Idealmente cualquiera de las tablas que han publicado, puse esa como ejemplo pues no he visto (fuera de lo de JNE que no es exportable) en un formato consumible en código. Las otras tablas ya las pusieron en un Google Docs (de donde he extraído los datos en el repo que mencioné), pero sería mejor que ustedes ofrecieran tods los datos como fuente de esta información recopilada.

**Comment by unrecano** [comment]
Se crea el pull request #10 para este requerimiento.

**Comment by jmcastagnetto** [comment]
¿Saben cuando va a estar esto en producción? -- Gracias de antemano

**Comment by aniversarioperu** [comment]
ya esta en produccion, gracias a @unrecano
