### ISSUE TITLE
agregar filtros por region a listados del home page

### ISSUE THREAD

**Issue by aniversarioperu** [aniversarioperu/otorongo.club#9]
ej este listado https://otorongo.club/2021/sentencias/ tiene filtro por region. Estos listados no tienen:

https://otorongo.club/2021/ingresos/

https://otorongo.club/2021/bienes/

**Comment by unrecano** [comment]
![Dibujo sin título](https://user-images.githubusercontent.com/4784511/107867925-602c8680-6e4d-11eb-8232-6a90944f3bda.jpg)

El pasar el valor "None" a la vista localmente me esta arrojando un error debido a que lo esta reconociendo como un valor valido ("None" de tipo str). Veo que esto no esta pasando en produccion lo que me parece raro. Sugiero que pudieramos controlar ese valor o vartir las vistas.

**Comment by unrecano** [comment]
Se crea el pull request #15 para resolver este issue.

**Comment by unrecano** [comment]
Un apunte chiquito en la url: https://otorongo.club/2021/sentencias/ al filtrar se visualiza un texto "None" debido a que no se esta pasando un id. Sugeriria trabajarlo con una vista diferente o pasar el id por un query param en la url para evitar pasar valores nulos.

![Dibujo sin título](https://user-images.githubusercontent.com/4784511/107868545-1e064380-6e53-11eb-927a-c78f48356b75.jpg)

**Comment by aniversarioperu** [comment]
Sí, tienes razon, hay que corregir eso. Se ve bien feo tener None en el URL.

**Comment by unrecano** [comment]
Se crea el pull request #19 para solucionar el None en URL enviandolo por query parameter.

**Comment by aniversarioperu** [comment]
gracias1
